import { describe, expect, it } from 'vitest'
import { PostgresSearchDriver, type PgClientLike } from '../src/index.js'

// The RLS fast path: when the search table is protected by row-level security,
// `tsv @@ …` cannot be an index condition (the `@@` operator is not LEAKPROOF),
// and the plan degrades to a sequential scan. Configured with `searchFunction`,
// the driver calls the SECURITY DEFINER function generated by
// `rlsSearchFunctionSql()` instead, which re-applies the tenant predicate
// itself and keeps the GIN index.

interface Call {
  text: string
  params?: unknown[] | undefined
}

class FakePg implements PgClientLike {
  readonly calls: Call[] = []
  rows: Record<string, unknown>[] = []
  async query(text: string, params?: unknown[]): Promise<{ rows: Record<string, unknown>[] }> {
    this.calls.push({ text, params })
    if (/count\(\*\)/.test(text)) return { rows: [{ total: this.rows.length }] }
    if (/^SELECT/.test(text)) return { rows: this.rows }
    return { rows: [] }
  }
  find(re: RegExp): Call | undefined {
    return this.calls.find((c) => re.test(c.text))
  }
}

const hit = (id: string, tenantId = 'acme', total = 1): Record<string, unknown> => ({
  tenant_id: tenantId,
  id,
  document: { id, tenantId, title: `Doc ${id}` },
  score: 0.5,
  total,
})

const driver = (
  pg: FakePg,
  searchFunction: NonNullable<ConstructorParameters<typeof PostgresSearchDriver>[0]['searchFunction']>,
) => new PostgresSearchDriver({ client: pg, searchFunction })

describe('PostgresSearchDriver with searchFunction (the RLS fast path)', () => {
  it('routes a text query through the function instead of the table', async () => {
    const pg = new FakePg()
    pg.rows = [hit('d1', 'acme', 2), hit('d2', 'acme', 2)]
    const result = await driver(pg, 'basalt_search_scoped').search('notes', { tenantId: 'acme', q: 'invoice' })

    const call = pg.find(/basalt_search_scoped/)
    expect(call).toBeDefined()
    expect(call!.text).toBe(
      'SELECT tenant_id, id, document, score, total FROM basalt_search_scoped($1, $2, $3::jsonb, $4, $5)',
    )
    expect(call!.params).toEqual(['invoice', 'notes', null, 20, 0])
    // and NOT the naked table query that would lose the index
    expect(pg.find(/FROM basalt_search WHERE/)).toBeUndefined()
    expect(result.hits.map((h) => h.id)).toEqual(['d1', 'd2'])
    expect(result.total).toBe(2)
  })

  it('passes NO tenant argument — the tenant can only come from the connection setting', async () => {
    const pg = new FakePg()
    pg.rows = [hit('d1')]
    await driver(pg, 'basalt_search_scoped').search('notes', { tenantId: 'acme', q: 'invoice' })
    expect(pg.find(/basalt_search_scoped/)!.params).not.toContain('acme')
  })

  it('takes the total from the function — one round trip, not two', async () => {
    const pg = new FakePg()
    pg.rows = [hit('d1', 'acme', 137)]
    const result = await driver(pg, 'basalt_search_scoped').search('notes', { tenantId: 'acme', q: 'invoice' })
    expect(result.total).toBe(137)
    expect(pg.calls).toHaveLength(1)
  })

  it('reports no matches as total 0', async () => {
    const pg = new FakePg()
    pg.rows = []
    const result = await driver(pg, 'basalt_search_scoped').search('notes', { tenantId: 'acme', q: 'nothing' })
    expect(result).toEqual({ hits: [], total: 0 })
  })

  it('sends filters as one jsonb argument, arrays intact', async () => {
    const pg = new FakePg()
    pg.rows = [hit('d1')]
    await driver(pg, 'basalt_search_scoped').search('notes', {
      tenantId: 'acme',
      q: 'invoice',
      filters: { folder: 'inbox', status: ['open', 'draft'], pinned: true },
    })
    const [, , filters] = pg.find(/basalt_search_scoped/)!.params as [string, string, string]
    expect(JSON.parse(filters)).toEqual({ folder: 'inbox', status: ['open', 'draft'], pinned: 'true' })
  })

  it('forwards limit and offset', async () => {
    const pg = new FakePg()
    pg.rows = [hit('d1')]
    await driver(pg, 'basalt_search_scoped').search('notes', { tenantId: 'acme', q: 'x', limit: 5, offset: 10 })
    expect(pg.find(/basalt_search_scoped/)!.params).toEqual(['x', 'notes', null, 5, 10])
  })

  it('refuses a row belonging to another tenant — fails closed on a misconfigured setting', async () => {
    const pg = new FakePg()
    pg.rows = [hit('d1', 'acme'), hit('g1', 'globex')]
    await expect(
      driver(pg, 'basalt_search_scoped').search('notes', { tenantId: 'acme', q: 'invoice' }),
    ).rejects.toThrow(/returned a row for tenant "globex" while searching "acme"/)
  })

  it('keeps the plain table query when there is no text to match', async () => {
    const pg = new FakePg()
    pg.rows = []
    // No `@@` in the plan, so no leakproof problem: equality on (idx, tenant_id)
    // is leakproof and RLS leaves the primary key alone.
    await driver(pg, 'basalt_search_scoped').search('notes', { tenantId: 'acme', q: '   ' })
    expect(pg.find(/basalt_search_scoped/)).toBeUndefined()
    expect(pg.find(/FROM basalt_search WHERE/)).toBeDefined()
  })

  it('accepts a schema-qualified function, by string or by object', async () => {
    const pg = new FakePg()
    pg.rows = [hit('d1')]
    await driver(pg, { name: 'basalt_search_scoped', schema: 'app' }).search('notes', { tenantId: 'acme', q: 'x' })
    expect(pg.find(/FROM app\.basalt_search_scoped\(/)).toBeDefined()

    const pg2 = new FakePg()
    pg2.rows = [hit('d1')]
    await driver(pg2, 'app.basalt_search_scoped').search('notes', { tenantId: 'acme', q: 'x' })
    expect(pg2.find(/FROM app\.basalt_search_scoped\(/)).toBeDefined()
  })

  it('validates the function name — it is interpolated, so it may not be attacker-shaped', () => {
    const pg = new FakePg()
    expect(() => driver(pg, 'fn(); DROP TABLE users; --')).toThrow(/invalid search function name/)
    expect(() => driver(pg, { name: 'ok', schema: 'a.b.c' })).toThrow(/invalid search function schema/)
    expect(() => driver(pg, 'a.b.c')).toThrow(/invalid search function name/)
  })

  it('leaves indexing, removal and the unfiltered path untouched', async () => {
    const pg = new FakePg()
    const d = driver(pg, 'basalt_search_scoped')
    await d.index('notes', { id: 'd1', tenantId: 'acme', title: 'Hello' })
    expect(pg.find(/INSERT INTO basalt_search/)).toBeDefined()
    await d.remove('notes', 'acme', 'd1')
    expect(pg.find(/DELETE FROM basalt_search/)).toBeDefined()
  })
})
