import { createHmac } from 'node:crypto'
import type { Drives } from './drives.js'
import { DriveNotificationInvalidError, DriveUnsupportedError } from './errors.js'
import type { DriveNotificationInput, DriveNotificationResult, DriveWatch } from './provider.js'
import { safeEqual } from './secret-box.js'
import type { DriveConnection } from './store.js'

/**
 * Inbound provider notifications.
 *
 * This is the one endpoint in the design that is **unauthenticated by
 * construction** — the provider calls it, and no session exists. So it is
 * treated as hostile, and every decision below follows from that:
 *
 * - **The notification is never trusted for content.** Not one of the three
 *   vendors sends the changed data; they send "something changed on channel X".
 *   So even a perfectly forged notification can only cause the app to *go and
 *   ask the provider* — using its own stored credentials, for its own tenant.
 *   The blast radius of a spoof is a wasted sync, not a data leak. That is a
 *   design property, not luck: treating the payload as data would hand an
 *   unauthenticated caller a write path.
 * - **Verification is pure.** `verifyNotification` gets no session and no
 *   network, so hammering the route cannot be amplified into provider traffic.
 * - **The channel secret identifies the connection.** A per-subscription random
 *   secret is generated by us, handed to the provider at subscribe time (Graph
 *   `clientState`, Google channel `token`), and compared in constant time on
 *   the way back. A caller who does not have it cannot address a connection at
 *   all — which also means they cannot make tenant A's connection sync by
 *   guessing an id.
 * - **Replays are bounded.** A repeated notification costs one extra sync of
 *   the same connection, and the cursor makes that a near-no-op. The optional
 *   {@link NotificationReplayGuard} collapses bursts outright.
 *
 * ## What the providers actually send
 *
 * - **Dropbox** — `X-Dropbox-Signature`, an HMAC-SHA256 of the **raw** body
 *   under the app secret, plus a `GET ?challenge=` echo that arrives *before*
 *   any connection exists (the URI is verified when it is saved in the App
 *   Console). This is the only one of the three with a real signature, which is
 *   why {@link verifyHmacSignature} exists here as a shared helper.
 *
 *   It is also the one that breaks the per-subscription-secret assumption: the
 *   webhook is registered once per **app**, so there is no subscription and no
 *   place to put a secret. The body names the *accounts* that changed
 *   (`list_folder.accounts`), and correlation runs through
 *   {@link DriveNotificationResult.accountIds} instead — which is why
 *   {@link DriveNotificationOutcome} returns a list of connections rather than
 *   one.
 * - **Microsoft Graph** — a `POST ?validationToken=` handshake that must be
 *   echoed as `text/plain` within seconds, then notifications carrying the
 *   `clientState` we chose. There is no signature; `clientState` *is* the
 *   authentication.
 * - **Google Drive** — `X-Goog-Channel-ID`, `X-Goog-Channel-Token` (our value),
 *   `X-Goog-Resource-State` and `X-Goog-Message-Number`. Also no signature.
 *
 * Two of the three therefore authenticate with a shared secret we generated,
 * which is exactly why the engine generates one per subscription rather than
 * letting an adapter choose.
 */

/** Collapses duplicate notifications. Back it with `@basaltkit/cache` in production. */
export interface NotificationReplayGuard {
  /** `true` the first time this key is seen within the window, `false` afterwards. */
  firstSeen(key: string, ttlMs: number): Promise<boolean>
}

/** In-memory replay guard — fine for one process, not for a cluster. */
export class MemoryReplayGuard implements NotificationReplayGuard {
  private readonly seen = new Map<string, number>()
  constructor(private readonly now: () => number = Date.now) {}

  async firstSeen(key: string, ttlMs: number): Promise<boolean> {
    const now = this.now()
    for (const [k, expiry] of this.seen) if (expiry <= now) this.seen.delete(k)
    if (this.seen.has(key)) return false
    this.seen.set(key, now + ttlMs)
    return true
  }
}

/**
 * What the engine knows about a verified notification, handed to a candidate
 * resolver so an app can fetch exactly the connections it might concern.
 *
 * Everything in it was **authenticated by the adapter** — an HMAC over the raw
 * body for Dropbox, a secret we generated for Graph and Google. Nothing here is
 * a value the caller merely asserted.
 */
export interface DriveNotificationQuery {
  provider: string
  /** Set when the route is scoped to one tenant. */
  tenantId?: string | undefined
  /** Provider subscription/channel id, when the notification named one. */
  watchId?: string | undefined
  /** Provider account ids the notification named — Dropbox's `dbid:…`. */
  accountIds?: readonly string[] | undefined
}

/**
 * Where candidate connections come from.
 *
 * An array for the simple case. A function for Dropbox, whose webhook URI is
 * registered once per *app*: a notification arrives naming account ids and no
 * tenant at all, so the app must look connections up by
 * `(provider, account.id)` — a lookup that necessarily spans tenants. That is
 * safe precisely because the id came from a signature-verified payload and
 * never from the caller, and it stays the **app's** query rather than becoming
 * a framework-wide table scan.
 */
export type DriveConnectionCandidates =
  | readonly DriveConnection[]
  | ((query: DriveNotificationQuery) => Promise<readonly DriveConnection[]> | readonly DriveConnection[])

export interface HandleNotificationOptions {
  /** The provider the route is mounted for. */
  provider: string
  /** Tenant to search when the app is multi-tenant and the route is per-tenant. Omit for a global route. */
  tenantId?: string
  /**
   * Candidate connections to match the notification against.
   *
   * Required and explicit, because the alternative — scanning every tenant's
   * connections from an unauthenticated endpoint — is precisely the
   * cross-tenant read this design refuses to have. An app with a per-tenant
   * callback URL passes that tenant's connections; an app with one global
   * callback passes a resolver (see {@link DriveConnectionCandidates}).
   */
  connections: DriveConnectionCandidates
  replayGuard?: NotificationReplayGuard
  /** Replay window. Default 5 minutes. */
  replayTtlMs?: number
}

export interface DriveNotificationOutcome {
  /** Answer the provider with this body and `content-type: text/plain`, then stop. */
  challenge?: string | undefined
  /**
   * The connections the notification concerns — empty when nothing matched.
   *
   * A list, not one connection: a Dropbox notification names *accounts*, and one
   * Dropbox account can be connected several times (two labels in one tenant,
   * or the same account connected by two tenants). Phase 1 returned a single
   * connection, which would have silently synced one of them and left the rest
   * stale.
   */
  connections: readonly DriveConnection[]
  /** Whether the app should schedule a sync. */
  shouldSync: boolean
  /**
   * Why nothing is going to happen, when `shouldSync` is false.
   *
   * `unmatched` is a *verified* notification that concerns no connection we
   * hold. It is deliberately not an error: answering it differently from a
   * matched one turns the endpoint into an oracle for "is this account/channel
   * connected here". The app may log it; the HTTP response must not differ.
   */
  reason?: 'challenge' | 'no-change' | 'replay' | 'unmatched' | undefined
}

/**
 * Verifies an inbound notification and resolves it to the connections it
 * concerns.
 *
 * Returns rather than throws for every outcome that a verified notification can
 * legitimately have (a handshake, a content-free ping, a replay, nothing that
 * matches); throws {@link DriveNotificationInvalidError} only when the
 * notification itself could not be *trusted* — a bad signature, a missing
 * channel secret, a body that is not a notification at all. A route answers the
 * first group with an identical 200 and the second with a flat 400.
 */
export async function handleNotification(
  drives: Drives,
  input: DriveNotificationInput,
  options: HandleNotificationOptions,
): Promise<DriveNotificationOutcome> {
  const provider = drives.internals.provider(options.provider)
  if (!provider.verifyNotification) throw new DriveUnsupportedError(provider.name, 'verifyNotification')

  let verified: DriveNotificationResult
  try {
    verified = provider.verifyNotification(input)
  } catch (error) {
    // An adapter that throws during verification is reporting a bad
    // notification, not a bug — normalise it so a route never leaks an
    // adapter's internal error text to an unauthenticated caller.
    throw error instanceof DriveNotificationInvalidError
      ? error
      : new DriveNotificationInvalidError('verification failed.')
  }

  if (verified.challenge !== undefined) {
    return { challenge: verified.challenge, connections: [], shouldSync: false, reason: 'challenge' }
  }
  if (
    verified.secret === undefined &&
    (verified.secrets === undefined || verified.secrets.length === 0) &&
    (verified.accountIds === undefined || verified.accountIds.length === 0)
  ) {
    // Neither correlation the contract offers. Whatever this is, it is not a
    // notification we can attribute, and guessing would mean syncing a
    // connection an unauthenticated caller picked.
    throw new DriveNotificationInvalidError('the notification carried nothing that identifies a connection.')
  }

  const query: DriveNotificationQuery = {
    provider: provider.name,
    ...(options.tenantId !== undefined ? { tenantId: options.tenantId } : {}),
    ...(verified.watchId !== undefined ? { watchId: verified.watchId } : {}),
    ...(verified.accountIds !== undefined ? { accountIds: verified.accountIds } : {}),
  }
  const candidates =
    typeof options.connections === 'function' ? await options.connections(query) : options.connections

  const matched = candidates.filter(
    (candidate) =>
      candidate.provider === provider.name &&
      (options.tenantId === undefined || candidate.tenantId === options.tenantId) &&
      matches(candidate, verified),
  )

  // Uniform answer whether nothing matched, the account belongs to another
  // tenant, or the resolver returned an empty set: the caller learns the same
  // thing in every case, which is nothing.
  if (matched.length === 0) return { connections: [], shouldSync: false, reason: 'unmatched' }
  if (!verified.changed) return { connections: matched, shouldSync: false, reason: 'no-change' }

  if (options.replayGuard) {
    // One key for the whole notification, not one per connection: a Dropbox
    // notification naming two accounts is one delivery, and collapsing it per
    // connection would let a replay through whenever the fan-out differed.
    const key = `${provider.name}:${matched.map((c) => `${c.tenantId}/${c.id}`).sort().join(',')}:${verified.watchId ?? ''}:${input.headers['x-goog-message-number'] ?? hashBody(input.body)}`
    if (!(await options.replayGuard.firstSeen(key, options.replayTtlMs ?? 5 * 60_000))) {
      return { connections: matched, shouldSync: false, reason: 'replay' }
    }
  }

  return { connections: matched, shouldSync: true }
}

/**
 * Whether one connection is the subject of a verified notification.
 *
 * Two correlations, and they are not interchangeable:
 *
 * - **A channel secret** — the value we generated at subscribe time and the
 *   provider echoed back. Compared in constant time, and only against a
 *   connection that actually holds a subscription.
 * - **A provider account id** — Dropbox, which has no per-subscription secret
 *   at all. Compared against `account.id`, which is recorded at connect time
 *   from the provider's own profile call, never from anything a caller sends.
 *   A connection with no recorded account can never match, so a missing
 *   `account.id` fails closed instead of matching everything.
 */
function matches(candidate: DriveConnection, verified: DriveNotificationResult): boolean {
  // One secret for an ordinary delivery, several when a provider batches
  // notifications for subscriptions that share a URL (Microsoft Graph does).
  const secrets = verified.secret !== undefined ? [verified.secret] : (verified.secrets ?? [])
  if (secrets.length > 0) {
    const watch = candidate.watch
    return (
      watch !== undefined &&
      secrets.some((secret) => safeEqual(watch.secret, secret)) &&
      // A batch names several subscriptions, so `watchId` is only reported
      // when every entry agreed on one; when it is absent the secret alone
      // decides, which is what it authenticates.
      (verified.watchId === undefined || watch.id === verified.watchId)
    )
  }
  const accountId = candidate.account?.id
  if (accountId === undefined || accountId === '') return false
  return (verified.accountIds ?? []).some((id) => safeEqual(id, accountId))
}

const hashBody = (body: Buffer): string => createHmac('sha256', 'drive-notification').update(body).digest('base64url')

/**
 * Constant-time HMAC check over a raw body — the Dropbox scheme, and the shape
 * any signed provider uses.
 *
 * Takes a `Buffer`, never a parsed object: re-serialising JSON changes the
 * bytes (key order, whitespace, unicode escapes) and the signature stops
 * matching for reasons nobody can debug. A route must therefore keep the raw
 * body, which is why {@link DriveNotificationInput.body} is typed the way it is.
 */
export function verifyHmacSignature(input: {
  body: Buffer
  signature: string | undefined
  secret: string
  algorithm?: string
  encoding?: 'hex' | 'base64'
}): boolean {
  if (input.signature === undefined || input.signature === '') return false
  const expected = createHmac(input.algorithm ?? 'sha256', input.secret)
    .update(input.body)
    .digest(input.encoding ?? 'hex')
  return safeEqual(input.signature.trim(), expected)
}

/**
 * Subscribes a connection to provider push notifications and persists the
 * subscription (including the secret the provider will echo back).
 *
 * The secret is generated here, never by the adapter: it is what authenticates
 * every later notification, and a per-subscription random value from one place
 * is the difference between "a caller needs 32 bytes of entropy" and "a caller
 * needs to guess whatever this adapter happened to use".
 */
export async function watchConnection(
  drives: Drives,
  connectionId: string,
  input: { notificationUrl: string; tenantId?: string; ttlMs?: number },
): Promise<DriveWatch> {
  const connection = await drives.internals.require(connectionId, input.tenantId, 'watch')
  const provider = drives.internals.provider(connection.provider)
  if (!provider.watch) throw new DriveUnsupportedError(provider.name, 'watch')
  const secret = drives.internals.newSecret()

  const watch = await drives.run(connection, (session) =>
    provider.watch!(session, {
      notificationUrl: input.notificationUrl,
      secret,
      ...(input.ttlMs !== undefined ? { ttlMs: input.ttlMs } : {}),
    }),
  )
  await drives.internals.store.update(connection.tenantId, connection.id, {
    watch: {
      id: watch.id,
      secret,
      ...(watch.expiresAt !== undefined ? { expiresAt: watch.expiresAt } : {}),
      ...(watch.raw !== undefined ? { raw: watch.raw } : {}),
    },
  })
  return watch
}
