import { createHmac } from 'node:crypto'
import type { Drives } from './drives.js'
import { DriveNotificationInvalidError, DriveUnsupportedError } from './errors.js'
import type { DriveNotificationInput, DriveNotificationResult, DriveWatch } from './provider.js'
import { safeEqual } from './secret-box.js'
import type { DriveConnection } from './store.js'

/**
 * Inbound provider notifications.
 *
 * This is the one endpoint in the design that is **unauthenticated by
 * construction** — the provider calls it, and no session exists. So it is
 * treated as hostile, and every decision below follows from that:
 *
 * - **The notification is never trusted for content.** Not one of the three
 *   vendors sends the changed data; they send "something changed on channel X".
 *   So even a perfectly forged notification can only cause the app to *go and
 *   ask the provider* — using its own stored credentials, for its own tenant.
 *   The blast radius of a spoof is a wasted sync, not a data leak. That is a
 *   design property, not luck: treating the payload as data would hand an
 *   unauthenticated caller a write path.
 * - **Verification is pure.** `verifyNotification` gets no session and no
 *   network, so hammering the route cannot be amplified into provider traffic.
 * - **The channel secret identifies the connection.** A per-subscription random
 *   secret is generated by us, handed to the provider at subscribe time (Graph
 *   `clientState`, Google channel `token`), and compared in constant time on
 *   the way back. A caller who does not have it cannot address a connection at
 *   all — which also means they cannot make tenant A's connection sync by
 *   guessing an id.
 * - **Replays are bounded.** A repeated notification costs one extra sync of
 *   the same connection, and the cursor makes that a near-no-op. The optional
 *   {@link NotificationReplayGuard} collapses bursts outright.
 *
 * ## What the providers actually send
 *
 * - **Dropbox** — `X-Dropbox-Signature`, an HMAC-SHA256 of the **raw** body
 *   under the app secret, plus a one-time `GET ?challenge=` echo when the URI
 *   is registered. This is the only one of the three with a real signature,
 *   which is why {@link verifyHmacSignature} exists here as a shared helper.
 * - **Microsoft Graph** — a `POST ?validationToken=` handshake that must be
 *   echoed as `text/plain` within seconds, then notifications carrying the
 *   `clientState` we chose. There is no signature; `clientState` *is* the
 *   authentication.
 * - **Google Drive** — `X-Goog-Channel-ID`, `X-Goog-Channel-Token` (our value),
 *   `X-Goog-Resource-State` and `X-Goog-Message-Number`. Also no signature.
 *
 * Two of the three therefore authenticate with a shared secret we generated,
 * which is exactly why the engine generates one per subscription rather than
 * letting an adapter choose.
 */

/** Collapses duplicate notifications. Back it with `@basaltkit/cache` in production. */
export interface NotificationReplayGuard {
  /** `true` the first time this key is seen within the window, `false` afterwards. */
  firstSeen(key: string, ttlMs: number): Promise<boolean>
}

/** In-memory replay guard — fine for one process, not for a cluster. */
export class MemoryReplayGuard implements NotificationReplayGuard {
  private readonly seen = new Map<string, number>()
  constructor(private readonly now: () => number = Date.now) {}

  async firstSeen(key: string, ttlMs: number): Promise<boolean> {
    const now = this.now()
    for (const [k, expiry] of this.seen) if (expiry <= now) this.seen.delete(k)
    if (this.seen.has(key)) return false
    this.seen.set(key, now + ttlMs)
    return true
  }
}

export interface HandleNotificationOptions {
  /** The provider the route is mounted for. */
  provider: string
  /** Tenant to search when the app is multi-tenant and the route is per-tenant. Omit for a global route. */
  tenantId?: string
  /**
   * Candidate connections to match the notification against.
   *
   * Required and explicit, because the alternative — scanning every tenant's
   * connections from an unauthenticated endpoint — is precisely the
   * cross-tenant read this design refuses to have. An app with a per-tenant
   * callback URL passes that tenant's connections; an app with one global
   * callback resolves the tenant from its own routing first.
   */
  connections: readonly DriveConnection[]
  replayGuard?: NotificationReplayGuard
  /** Replay window. Default 5 minutes. */
  replayTtlMs?: number
}

export interface DriveNotificationOutcome {
  /** Answer the provider with this body and `content-type: text/plain`, then stop. */
  challenge?: string | undefined
  /** The connection the notification belongs to, when one matched. */
  connection?: DriveConnection | undefined
  /** Whether the app should schedule a sync. */
  shouldSync: boolean
  /** Why nothing is going to happen, when `shouldSync` is false. */
  reason?: 'challenge' | 'no-change' | 'replay' | undefined
}

/**
 * Verifies an inbound notification and resolves it to a connection.
 *
 * Returns rather than throws for the benign outcomes (a handshake, a
 * content-free ping, a replay); throws {@link DriveNotificationInvalidError}
 * only when the notification cannot be trusted, which a route should answer
 * with a flat 400 and no detail.
 */
export async function handleNotification(
  drives: Drives,
  input: DriveNotificationInput,
  options: HandleNotificationOptions,
): Promise<DriveNotificationOutcome> {
  const provider = drives.internals.provider(options.provider)
  if (!provider.verifyNotification) throw new DriveUnsupportedError(provider.name, 'verifyNotification')

  let verified: DriveNotificationResult
  try {
    verified = provider.verifyNotification(input)
  } catch (error) {
    // An adapter that throws during verification is reporting a bad
    // notification, not a bug — normalise it so a route never leaks an
    // adapter's internal error text to an unauthenticated caller.
    throw error instanceof DriveNotificationInvalidError
      ? error
      : new DriveNotificationInvalidError('verification failed.')
  }

  if (verified.challenge !== undefined) {
    return { challenge: verified.challenge, shouldSync: false, reason: 'challenge' }
  }
  if (verified.secret === undefined) {
    throw new DriveNotificationInvalidError('the notification carried no channel secret.')
  }

  // Constant-time match against the subscriptions we actually registered. The
  // scan is over a caller-supplied candidate list, never the whole table.
  const connection = options.connections.find(
    (candidate) =>
      candidate.provider === provider.name &&
      candidate.watch !== undefined &&
      safeEqual(candidate.watch.secret, verified.secret as string) &&
      (verified.watchId === undefined || candidate.watch.id === verified.watchId) &&
      (options.tenantId === undefined || candidate.tenantId === options.tenantId),
  )
  if (!connection) throw new DriveNotificationInvalidError('no connection matches this notification.')
  if (!verified.changed) return { connection, shouldSync: false, reason: 'no-change' }

  if (options.replayGuard) {
    const key = `${connection.tenantId}:${connection.id}:${verified.watchId ?? ''}:${input.headers['x-goog-message-number'] ?? hashBody(input.body)}`
    if (!(await options.replayGuard.firstSeen(key, options.replayTtlMs ?? 5 * 60_000))) {
      return { connection, shouldSync: false, reason: 'replay' }
    }
  }

  return { connection, shouldSync: true }
}

const hashBody = (body: Buffer): string => createHmac('sha256', 'drive-notification').update(body).digest('base64url')

/**
 * Constant-time HMAC check over a raw body — the Dropbox scheme, and the shape
 * any signed provider uses.
 *
 * Takes a `Buffer`, never a parsed object: re-serialising JSON changes the
 * bytes (key order, whitespace, unicode escapes) and the signature stops
 * matching for reasons nobody can debug. A route must therefore keep the raw
 * body, which is why {@link DriveNotificationInput.body} is typed the way it is.
 */
export function verifyHmacSignature(input: {
  body: Buffer
  signature: string | undefined
  secret: string
  algorithm?: string
  encoding?: 'hex' | 'base64'
}): boolean {
  if (input.signature === undefined || input.signature === '') return false
  const expected = createHmac(input.algorithm ?? 'sha256', input.secret)
    .update(input.body)
    .digest(input.encoding ?? 'hex')
  return safeEqual(input.signature.trim(), expected)
}

/**
 * Subscribes a connection to provider push notifications and persists the
 * subscription (including the secret the provider will echo back).
 *
 * The secret is generated here, never by the adapter: it is what authenticates
 * every later notification, and a per-subscription random value from one place
 * is the difference between "a caller needs 32 bytes of entropy" and "a caller
 * needs to guess whatever this adapter happened to use".
 */
export async function watchConnection(
  drives: Drives,
  connectionId: string,
  input: { notificationUrl: string; tenantId?: string; ttlMs?: number },
): Promise<DriveWatch> {
  const connection = await drives.internals.require(connectionId, input.tenantId, 'watch')
  const provider = drives.internals.provider(connection.provider)
  if (!provider.watch) throw new DriveUnsupportedError(provider.name, 'watch')
  const secret = drives.internals.newSecret()

  const watch = await drives.run(connection, (session) =>
    provider.watch!(session, {
      notificationUrl: input.notificationUrl,
      secret,
      ...(input.ttlMs !== undefined ? { ttlMs: input.ttlMs } : {}),
    }),
  )
  await drives.internals.store.update(connection.tenantId, connection.id, {
    watch: {
      id: watch.id,
      secret,
      ...(watch.expiresAt !== undefined ? { expiresAt: watch.expiresAt } : {}),
      ...(watch.raw !== undefined ? { raw: watch.raw } : {}),
    },
  })
  return watch
}
