import { defineConfig } from 'vitepress'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const github = 'https://github.com/Zebedeu/basalt'

// The umbrella "Basalt release" version — a single marketing/docs marker. The
// `@basaltkit/*` packages are versioned INDEPENDENTLY (see the Ecosystem page);
// this is read from the private root package.json so the nav never drifts from it.
const rootPkg = JSON.parse(
  readFileSync(fileURLToPath(new URL('../../../package.json', import.meta.url)), 'utf8'),
) as { version: string }
const basaltRelease = rootPkg.version.split('.').slice(0, 2).join('.') // "1.1.0" → "1.1"

// The typedoc API sidebar is generated by `docs:api` (gitignored). Load it if
// present so `vitepress dev` works before generation; the build always runs
// docs:api first, so the reference is populated in production.
let apiSidebar: unknown[] = []
try {
  apiSidebar = JSON.parse(
    readFileSync(fileURLToPath(new URL('../reference/api/typedoc-sidebar.json', import.meta.url)), 'utf8'),
  ) as unknown[]
} catch {
  apiSidebar = []
}

// The per-package reference pages are generated by `docs:packages` (gitignored),
// one mirrored README each. Load its sidebar if present (dev before generation).
let packagesSidebar: unknown[] = []
try {
  packagesSidebar = JSON.parse(
    readFileSync(fileURLToPath(new URL('../reference/packages/packages-sidebar.json', import.meta.url)), 'utf8'),
  ) as unknown[]
} catch {
  packagesSidebar = []
}

// Search: Algolia DocSearch when credentials are present (production), otherwise
// the built-in local index — so the site always builds, with or without keys.
// Set ALGOLIA_APP_ID / ALGOLIA_API_KEY / ALGOLIA_INDEX in the deploy environment.
const algoliaAppId = process.env.ALGOLIA_APP_ID
const algoliaApiKey = process.env.ALGOLIA_API_KEY
const algoliaIndex = process.env.ALGOLIA_INDEX
const search =
  algoliaAppId && algoliaApiKey && algoliaIndex
    ? ({
        provider: 'algolia',
        options: {
          appId: algoliaAppId,
          apiKey: algoliaApiKey,
          indexName: algoliaIndex,
          // Localised placeholders for the DocSearch modal.
          locales: {
            pt: {
              placeholder: 'Pesquisar na documentação',
              translations: { button: { buttonText: 'Pesquisar' } },
            },
          },
        },
      } as const)
    : ({ provider: 'local' } as const)

export default defineConfig({
  title: 'Basalt',
  description: 'The complete toolkit for building SaaS on Node.js.',
  lang: 'en-US',
  // Served at the domain root (Cloudflare Pages / Netlify / Vercel), so base is '/'.
  cleanUrls: true,
  lastUpdated: true,

  // The generated typedoc API reference embeds example URLs (localhost OTLP
  // endpoints, etc.) as default values; those aren't navigable doc links, so
  // ignore localhost/127.0.0.1 while keeping dead-link checking everywhere else.
  ignoreDeadLinks: [/^https?:\/\/localhost/, /^https?:\/\/127\.0\.0\.1/],

  // English is the root locale (served at `/`); Portuguese lives under `/pt/`.
  // The root inherits the shared `themeConfig` below; `pt` overrides nav/sidebar.
  locales: {
    root: { label: 'English', lang: 'en-US' },
    pt: {
      label: 'Português',
      lang: 'pt-PT',
      link: '/pt/',
      description: 'O toolkit completo para construir SaaS em Node.js.',
      themeConfig: {
        nav: [
          { text: 'Guia', link: '/pt/guide/getting-started' },
          { text: 'Cookbook', link: '/pt/cookbook/notes-saas' },
          { text: 'Referência', link: '/pt/reference/packages' },
          { text: 'API', link: '/reference/api/' },
          { text: `Basalt ${basaltRelease}`, link: '/pt/guide/versioning' },
        ],
        sidebar: {
          '/pt/guide/': [
            {
              text: 'Começar',
              items: [
                { text: 'Introdução', link: '/pt/guide/getting-started' },
                { text: 'Instalação', link: '/pt/guide/installation' },
                { text: 'Conceitos centrais', link: '/pt/guide/concepts' },
                { text: 'Adaptadores HTTP', link: '/pt/guide/adapters' },
                { text: 'Perguntas frequentes (FAQ)', link: '/pt/guide/faq' },
                { text: 'Para além do SaaS', link: '/pt/guide/beyond-saas' },
                { text: 'Comparação com outras frameworks', link: '/pt/guide/comparison' },
              ],
            },
            {
              text: 'Experiência de desenvolvimento',
              items: [{ text: 'Desenvolvimento assistido por IA', link: '/pt/guide/ai' }],
            },
            {
              text: 'Blocos de SaaS',
              items: [
                { text: 'Multi-tenancy', link: '/pt/guide/tenancy' },
                { text: 'Criar um tenant', link: '/pt/guide/creating-a-tenant' },
                { text: 'Autenticação', link: '/pt/guide/auth' },
                { text: 'Equipas', link: '/pt/guide/teams' },
                { text: 'Subscrições', link: '/pt/guide/billing' },
                { text: 'Pagamentos por referência', link: '/pt/guide/reference-payments' },
                { text: 'Feature Flags', link: '/pt/guide/feature-flags' },
                { text: 'Webhooks', link: '/pt/guide/webhooks' },
              ],
            },
            {
              text: 'Frontend',
              items: [
                { text: 'Web UI & componentes', link: '/pt/guide/web-ui' },
                { text: 'UIs autónomas', link: '/pt/guide/admin-pages' },
              ],
            },
            {
              text: 'Dados & infraestrutura',
              items: [
                { text: 'Filas & Jobs', link: '/pt/guide/queues' },
                { text: 'Storage', link: '/pt/guide/storage' },
                { text: 'Caching', link: '/pt/guide/caching' },
                { text: 'Base de dados por tenant', link: '/pt/guide/database-per-tenant' },
              ],
            },
            {
              text: 'Capacidades',
              items: [
                { text: 'Realtime', link: '/pt/guide/realtime' },
                { text: 'Pesquisa', link: '/pt/guide/search' },
                { text: 'Upload de ficheiros', link: '/pt/guide/files' },
                { text: 'Comentários', link: '/pt/guide/comments' },
                { text: 'Internacionalização', link: '/pt/guide/i18n' },
                { text: 'Exportação de dados', link: '/pt/guide/exports' },
              ],
            },
            {
              text: 'Produção',
              items: [
                { text: 'Persistência & stores duráveis', link: '/pt/guide/persistence' },
                { text: 'Versionamento & compatibilidade', link: '/pt/guide/versioning' },
                { text: 'Ir para Produção', link: '/pt/guide/production' },
                { text: 'Segurança', link: '/pt/guide/security' },
                { text: 'Observabilidade', link: '/pt/guide/observability' },
                { text: 'OpenAPI', link: '/pt/guide/openapi' },
              ],
            },
          ],
          '/pt/cookbook/': [
            {
              text: 'Cookbook',
              items: [
                { text: 'Construir um SaaS de notas (ponta a ponta)', link: '/pt/cookbook/notes-saas' },
                { text: 'Um SaaS multi-tenant', link: '/pt/cookbook/multi-tenant-saas' },
                { text: 'Reforçar contas & faturação', link: '/pt/cookbook/account-lifecycle' },
              ],
            },
          ],
          '/pt/reference/': [
            {
              text: 'Referência',
              items: [{ text: 'Pacotes', link: '/pt/reference/packages' },
                { text: 'Ecossistema', link: '/pt/guide/ecosystem' }],
            },
          ],
        },
        editLink: {
          pattern: `${github}/edit/main/apps/docs/:path`,
          text: 'Editar esta página no GitHub',
        },
        footer: {
          message: 'Publicado sob a licença MIT.',
          copyright: 'Copyright © 2026 Basalt Contributors',
        },
        docFooter: { prev: 'Página anterior', next: 'Próxima página' },
        outline: { label: 'Nesta página' },
        returnToTopLabel: 'Voltar ao topo',
        langMenuLabel: 'Mudar idioma',
      },
    },
  },

  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Cookbook', link: '/cookbook/notes-saas' },
      { text: 'Reference', link: '/reference/packages' },
      { text: 'API', link: '/reference/api/' },
      { text: `Basalt ${basaltRelease}`, link: '/guide/versioning' },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Getting Started',
          items: [
            { text: 'Introduction', link: '/guide/getting-started' },
            { text: 'Installation', link: '/guide/installation' },
            { text: 'Core Concepts', link: '/guide/concepts' },
            { text: 'HTTP Adapters', link: '/guide/adapters' },
            { text: 'FAQ', link: '/guide/faq' },
            { text: 'Beyond SaaS', link: '/guide/beyond-saas' },
            { text: 'vs other frameworks', link: '/guide/comparison' },
          ],
        },
        {
          text: 'Developer Experience',
          items: [{ text: 'AI-assisted development', link: '/guide/ai' }],
        },
        {
          text: 'SaaS Building Blocks',
          items: [
            { text: 'Multi-tenancy', link: '/guide/tenancy' },
            { text: 'Creating a tenant', link: '/guide/creating-a-tenant' },
            { text: 'Authentication', link: '/guide/auth' },
            { text: 'Teams', link: '/guide/teams' },
            { text: 'Subscriptions', link: '/guide/billing' },
            { text: 'Reference & mobile-money payments', link: '/guide/reference-payments' },
            { text: 'Feature Flags', link: '/guide/feature-flags' },
            { text: 'Webhooks', link: '/guide/webhooks' },
          ],
        },
        {
          text: 'Frontend',
          items: [
            { text: 'Web UI & components', link: '/guide/web-ui' },
            { text: 'Self-contained UIs', link: '/guide/admin-pages' },
          ],
        },
        {
          text: 'Data & infrastructure',
          items: [
            { text: 'Queues & Jobs', link: '/guide/queues' },
            { text: 'Storage', link: '/guide/storage' },
            { text: 'Caching', link: '/guide/caching' },
            { text: 'Database-per-tenant', link: '/guide/database-per-tenant' },
          ],
        },
        {
          text: 'Capabilities',
          items: [
            { text: 'Realtime', link: '/guide/realtime' },
            { text: 'Search', link: '/guide/search' },
            { text: 'File uploads', link: '/guide/files' },
            { text: 'Comments', link: '/guide/comments' },
            { text: 'Internationalization', link: '/guide/i18n' },
            { text: 'Data exports', link: '/guide/exports' },
          ],
        },
        {
          text: 'Production',
          items: [
            { text: 'Persistence & durable stores', link: '/guide/persistence' },
            { text: 'Versioning & compatibility', link: '/guide/versioning' },
            { text: 'Going to Production', link: '/guide/production' },
            { text: 'Security', link: '/guide/security' },
            { text: 'Observability', link: '/guide/observability' },
            { text: 'OpenAPI', link: '/guide/openapi' },
          ],
        },
      ],
      '/cookbook/': [
        {
          text: 'Cookbook',
          items: [
            { text: 'Build a notes SaaS (end to end)', link: '/cookbook/notes-saas' },
            { text: 'A multi-tenant SaaS', link: '/cookbook/multi-tenant-saas' },
            { text: 'Harden accounts & billing', link: '/cookbook/account-lifecycle' },
          ],
        },
      ],
      ...(apiSidebar.length ? { '/reference/api/': apiSidebar as never } : {}),
      ...(packagesSidebar.length ? { '/reference/packages': packagesSidebar as never } : {}),
      '/reference/': [
        {
          text: 'Reference',
          items: [{ text: 'Packages', link: '/reference/packages' },
            { text: 'Ecosystem', link: '/guide/ecosystem' }],
        },
      ],
    },

    socialLinks: [{ icon: 'github', link: github }],

    editLink: {
      pattern: `${github}/edit/main/apps/docs/:path`,
      text: 'Edit this page on GitHub',
    },

    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © 2026 Basalt Contributors',
    },

    search,
  },
})
