import { createHmac } from 'node:crypto'
import { describe, expect, it } from 'vitest'
import { DriveNotificationInvalidError } from '../src/errors.js'
import {
  MemoryReplayGuard,
  handleNotification,
  verifyHmacSignature,
  watchConnection,
} from '../src/notifications.js'
import { connect, harness } from './helpers.js'

const NOTIFICATION_URL = 'https://app.test/drives/fake/notify'

async function watched() {
  const h = harness({ provider: { files: [{ externalId: 'f1', name: 'a.txt' }] } })
  const view = await connect(h, { tenantId: 'acme' })
  const watch = await watchConnection(h.drives, view.id, { tenantId: 'acme', notificationUrl: NOTIFICATION_URL })
  const connections = [(await h.store.find('acme', view.id))!]
  return { h, view, watch, connections }
}

describe('watchConnection', () => {
  it('registers a subscription and persists it with a generated secret', async () => {
    const { h, view, watch } = await watched()
    const stored = await h.store.find('acme', view.id)

    expect(watch.id).toBeTruthy()
    expect(stored?.watch?.id).toBe(watch.id)
    // The secret is generated by the engine, not by the adapter: it is what
    // authenticates every later notification.
    expect(stored?.watch?.secret).toMatch(/^[A-Za-z0-9_-]{20,}$/)
    expect(h.fake.watches.get(watch.id)?.secret).toBe(stored?.watch?.secret)
  })

  it('never exposes the subscription secret through the connection view', async () => {
    const { h, view } = await watched()
    const listed = (await h.drives.list({ tenantId: 'acme' }))[0]!
    expect(listed.watching).toBe(true)
    expect(JSON.stringify(listed)).not.toContain((await h.store.find('acme', view.id))!.watch!.secret)
  })

  it('cannot watch another tenant’s connection', async () => {
    const h = harness()
    const view = await connect(h, { tenantId: 'acme' })
    await expect(
      watchConnection(h.drives, view.id, { tenantId: 'globex', notificationUrl: NOTIFICATION_URL }),
    ).rejects.toMatchObject({ code: 'DRIVE_CONNECTION_NOT_FOUND' })
  })

  it('reports the capability as unsupported when the adapter has no watch', async () => {
    const h = harness({ provider: { supportsWatch: false } })
    const view = await connect(h, { tenantId: 'acme' })
    await expect(
      watchConnection(h.drives, view.id, { tenantId: 'acme', notificationUrl: NOTIFICATION_URL }),
    ).rejects.toMatchObject({ code: 'DRIVE_UNSUPPORTED' })
  })
})

describe('handleNotification', () => {
  it('resolves a valid notification to its connection', async () => {
    const { h, view, watch, connections } = await watched()
    const outcome = await handleNotification(h.drives, h.fake.notificationFor(watch.id), {
      provider: 'fake',
      connections,
    })

    expect(outcome.shouldSync).toBe(true)
    expect(outcome.connection?.id).toBe(view.id)
  })

  it('answers a handshake challenge without touching any connection', async () => {
    const { h, connections } = await watched()
    const outcome = await handleNotification(
      h.drives,
      { method: 'GET', headers: {}, query: { challenge: 'echo-me' }, body: Buffer.alloc(0) },
      { provider: 'fake', connections },
    )

    // Microsoft Graph's validationToken and Dropbox's GET challenge both land
    // here: answer verbatim as text/plain and do nothing else.
    expect(outcome.challenge).toBe('echo-me')
    expect(outcome.shouldSync).toBe(false)
    expect(outcome.reason).toBe('challenge')
  })

  describe('spoofing', () => {
    it('refuses a notification with no channel secret', async () => {
      const { h, connections } = await watched()
      await expect(
        handleNotification(
          h.drives,
          { method: 'POST', headers: {}, query: {}, body: Buffer.from('{}') },
          { provider: 'fake', connections },
        ),
      ).rejects.toThrow(DriveNotificationInvalidError)
    })

    it('refuses a forged channel secret', async () => {
      const { h, watch, connections } = await watched()
      const forged = h.fake.notificationFor(watch.id)
      forged.headers['x-fake-channel-token'] = 'guessed-token'
      await expect(handleNotification(h.drives, forged, { provider: 'fake', connections })).rejects.toThrow(
        DriveNotificationInvalidError,
      )
    })

    it('refuses a valid secret paired with someone else’s channel id', async () => {
      const { h, watch, connections } = await watched()
      const mixed = h.fake.notificationFor(watch.id)
      mixed.headers['x-fake-channel-id'] = 'channel-999'
      await expect(handleNotification(h.drives, mixed, { provider: 'fake', connections })).rejects.toThrow(
        DriveNotificationInvalidError,
      )
    })

    it('cannot reach a connection that is not in the candidate list', async () => {
      // The route scopes the candidates. An unauthenticated caller therefore
      // cannot address another tenant's connection at all — there is no path
      // from this endpoint to a cross-tenant read.
      const { h, watch } = await watched()
      await expect(
        handleNotification(h.drives, h.fake.notificationFor(watch.id), { provider: 'fake', connections: [] }),
      ).rejects.toThrow(DriveNotificationInvalidError)
    })

    it('does not match a connection belonging to a different tenant', async () => {
      const { h, watch, connections } = await watched()
      await expect(
        handleNotification(h.drives, h.fake.notificationFor(watch.id), {
          provider: 'fake',
          tenantId: 'globex',
          connections,
        }),
      ).rejects.toThrow(DriveNotificationInvalidError)
    })

    it('never causes a download — a notification is a hint, never data', async () => {
      const { h, watch, connections } = await watched()
      await handleNotification(h.drives, h.fake.notificationFor(watch.id), { provider: 'fake', connections })
      // The blast radius of a perfectly forged notification is a wasted sync.
      expect(h.fake.calls['download']).toBeUndefined()
    })
  })

  describe('replay', () => {
    it('collapses a repeated notification when a guard is supplied', async () => {
      const { h, watch, connections } = await watched()
      const guard = new MemoryReplayGuard(h.now)
      const notification = h.fake.notificationFor(watch.id, { messageNumber: 7 })

      const first = await handleNotification(h.drives, notification, { provider: 'fake', connections, replayGuard: guard })
      const second = await handleNotification(h.drives, notification, { provider: 'fake', connections, replayGuard: guard })

      expect(first.shouldSync).toBe(true)
      expect(second.shouldSync).toBe(false)
      expect(second.reason).toBe('replay')
    })

    it('lets a genuinely new notification through', async () => {
      const { h, watch, connections } = await watched()
      const guard = new MemoryReplayGuard(h.now)
      await handleNotification(h.drives, h.fake.notificationFor(watch.id, { messageNumber: 1 }), {
        provider: 'fake',
        connections,
        replayGuard: guard,
      })
      const next = await handleNotification(h.drives, h.fake.notificationFor(watch.id, { messageNumber: 2 }), {
        provider: 'fake',
        connections,
        replayGuard: guard,
      })
      expect(next.shouldSync).toBe(true)
    })

    it('forgets an entry once its window has passed', async () => {
      let clock = 1_000_000
      const guard = new MemoryReplayGuard(() => clock)
      expect(await guard.firstSeen('k', 1000)).toBe(true)
      expect(await guard.firstSeen('k', 1000)).toBe(false)
      clock += 2000
      expect(await guard.firstSeen('k', 1000)).toBe(true)
    })
  })

  it('reports a content-free ping as nothing to do', async () => {
    const { h, watch, connections } = await watched()
    const sync = h.fake.notificationFor(watch.id, { state: 'sync' })
    const outcome = await handleNotification(h.drives, sync, { provider: 'fake', connections })
    expect(outcome.shouldSync).toBe(false)
    expect(outcome.reason).toBe('no-change')
  })

  it('reports the capability as unsupported when the adapter cannot verify', async () => {
    const h = harness({ provider: { supportsWatch: false } })
    const bare = h.fake as unknown as Record<string, unknown>
    bare['verifyNotification'] = undefined
    await expect(
      handleNotification(
        h.drives,
        { method: 'POST', headers: {}, query: {}, body: Buffer.alloc(0) },
        { provider: 'fake', connections: [] },
      ),
    ).rejects.toMatchObject({ code: 'DRIVE_UNSUPPORTED' })
  })
})

describe('verifyHmacSignature', () => {
  const secret = 'app-secret'
  const body = Buffer.from('{"list_folder":{"accounts":["a1"]}}')
  const valid = (): string => createHmac('sha256', secret).update(body).digest('hex')

  it('accepts a correct signature over the RAW body', () => {
    expect(verifyHmacSignature({ body, signature: valid(), secret })).toBe(true)
  })

  it('rejects a wrong signature', () => {
    expect(verifyHmacSignature({ body, signature: 'deadbeef', secret })).toBe(false)
  })

  it('rejects a missing signature rather than passing', () => {
    expect(verifyHmacSignature({ body, signature: undefined, secret })).toBe(false)
    expect(verifyHmacSignature({ body, signature: '', secret })).toBe(false)
  })

  it('rejects a signature computed over re-serialised JSON', () => {
    // The reason DriveNotificationInput.body is a Buffer: re-serialising
    // changes the bytes (key order, whitespace) and the signature stops
    // matching for reasons nobody can debug.
    const reserialised = Buffer.from(JSON.stringify(JSON.parse(body.toString()), null, 2))
    const wrong = createHmac('sha256', secret).update(reserialised).digest('hex')
    expect(verifyHmacSignature({ body, signature: wrong, secret })).toBe(false)
  })

  it('rejects a signature made with another secret', () => {
    const other = createHmac('sha256', 'other').update(body).digest('hex')
    expect(verifyHmacSignature({ body, signature: other, secret })).toBe(false)
  })

  it('supports base64 encoding', () => {
    const b64 = createHmac('sha256', secret).update(body).digest('base64')
    expect(verifyHmacSignature({ body, signature: b64, secret, encoding: 'base64' })).toBe(true)
  })
})
