// Copies the production stubs (Dockerfile, .dockerignore, CI workflow) from
// @basaltkit/cli — their single source of truth, also served by
// `basalt publish` — into src/stubs.ts, so create-basalt can ship them in a new
// scaffold and offer them from `update` while staying dependency-free. Runs
// before every build; tests/production.test.ts fails if the copy drifts.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const source = join(here, '..', '..', 'cli', 'src', 'stubs.ts')
const target = join(here, '..', 'src', 'stubs.ts')

const STUBS_HEADER =
  '// GENERATED by scripts/sync-stubs.mjs from packages/cli/src/stubs.ts (runs before every build) — do not edit.\n'

writeFileSync(target, STUBS_HEADER + readFileSync(source, 'utf8'))
