// GENERATED by scripts/sync-stubs.mjs from packages/cli/src/stubs.ts (runs before every build) — do not edit.
/**
 * The production stubs `basalt publish` copies into an app — the SINGLE source
 * of truth. create-basalt ships the same files in every new scaffold and offers
 * them from `create-basalt update`: its build copies this file verbatim to
 * `packages/create-app/src/stubs.ts` (scripts/sync-stubs.mjs), and a test there
 * fails if the copy drifts. Keep this module free of imports for that reason.
 *
 * The layout these stubs assume is the create-basalt scaffold's (BK-026):
 * `pnpm build` runs `tsc -p tsconfig.build.json` (rootDir `.`, outDir `dist`),
 * so `src/server.ts` compiles to {@link PRODUCTION_ENTRY}; `pnpm start` runs it
 * with plain `node` — no tsx, no TypeScript at runtime. A Prisma client, when
 * there is one, is generated OUTSIDE `src/` (`generated/prisma`) and imported
 * through the package.json `imports` alias `#db/*`, so it resolves the same
 * from `src/` (tsx) and from `dist/src/` (node).
 */

/** The compiled server entry the Dockerfile runs and the scaffold's `start` script points at. */
export const PRODUCTION_ENTRY = 'dist/src/server.js'

/** Multi-stage production image: build with the dev toolchain, run on plain node as a non-root user. */
export const DOCKERFILE = `# syntax=docker/dockerfile:1
# Production image for a Basalt app (the create-basalt layout): \`pnpm build\`
# compiles src/ to dist/ and the image runs ${PRODUCTION_ENTRY} on plain
# node — no tsx, no TypeScript at runtime.
#
#   docker build -t my-app .
#   docker run -p 3000:3000 -e APP_SECRET=… -e DATABASE_URL=… my-app
#
# Configuration comes from the environment (nothing loads .env here, and
# .dockerignore keeps it out of the image). Database migrations are NOT run
# by the image: apply them before rolling out (\`pnpm db:deploy\` in CI).
#
# Installs with pnpm from pnpm-lock.yaml. An app on npm/yarn/bun replaces the
# pnpm install / exec / run / prune lines with its own package manager's.
ARG NODE_VERSION=22
ARG PNPM_VERSION=11

FROM node:\${NODE_VERSION}-slim AS build
ARG PNPM_VERSION
# Non-interactive pnpm: without it \`pnpm prune\` in a workspace (a --ui app's
# web/) aborts with ERR_PNPM_ABORTED_REMOVE_MODULES_DIR_NO_TTY.
ENV CI=true
WORKDIR /app
RUN npm install -g pnpm@\${PNPM_VERSION}
COPY . .
# Full install: the build needs the devDependencies (typescript, prisma).
RUN pnpm install --frozen-lockfile
# The Prisma client (when the app has a schema) is generated into ./generated.
RUN if [ -f prisma/schema.prisma ]; then pnpm exec prisma generate; fi && mkdir -p generated
RUN pnpm run build
# Drop the devDependencies (tsx, typescript, prisma CLI, generators, the AI
# bridge): none of them may ship. --ignore-scripts keeps the app's postinstall
# (\`prisma generate\`, a dev tool) from running again.
RUN pnpm prune --prod --ignore-scripts

FROM node:\${NODE_VERSION}-slim AS run
ENV NODE_ENV=production
ENV PORT=3000
# Path the HEALTHCHECK probes: the scaffold's /health route by default; set
# /readyz when the app registers healthPlugin().
ENV HEALTHCHECK_PATH=/health
WORKDIR /app
COPY --from=build --chown=node:node /app/package.json ./package.json
COPY --from=build --chown=node:node /app/node_modules ./node_modules
COPY --from=build --chown=node:node /app/generated ./generated
COPY --from=build --chown=node:node /app/dist ./dist
USER node
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \\
  CMD node -e "fetch('http://127.0.0.1:' + (process.env.PORT || 3000) + process.env.HEALTHCHECK_PATH).then((r) => process.exit(r.ok ? 0 : 1), () => process.exit(1))"
CMD ["node", "--enable-source-maps", "${PRODUCTION_ENTRY}"]
`

/**
 * Published with the Dockerfile: its \`COPY . .\` would otherwise bake \`.env\`,
 * private keys and VCS metadata into an image layer. Every secret rule is
 * \`**\/\`-prefixed: .dockerignore patterns are anchored at the context root, so
 * a bare \`.env\` or \`*.pem\` would still let \`prisma/.env\` or
 * \`certs/server.key\` through. \`dist\` is rebuilt inside the image.
 */
export const DOCKERIGNORE = `**/.env
**/.env.*
!**/.env.example
**/.npmrc
**/.git
**/node_modules
**/coverage
**/*.log
**/*.pem
**/*.key
**/*.p12
**/*.pfx
**/.DS_Store
dist
`

/** GitHub Actions CI: install, typecheck, build (the production path), test. */
export const CI_WORKFLOW = `name: ci
on:
  push: { branches: [main] }
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Drop \`with: version\` if package.json declares a packageManager.
      - uses: pnpm/action-setup@v4
        with: { version: 11 }
      - uses: actions/setup-node@v4
        with: { node-version: 22, cache: pnpm }
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck
      - run: pnpm run build
      - run: pnpm run test
`

export const EDITORCONFIG = `root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
trim_trailing_whitespace = true
`
