// GENERATED by scripts/sync-versions.mjs (runs before every build) — do not edit.
// The dependency range a new app gets for each @basaltkit/* package: the
// current release line (^<major>.<minor>.0) of the workspace version.
export const SCAFFOLD_VERSIONS: Readonly<Record<string, string>> = {
  '@basaltkit/admin': '^2.0.0',
  '@basaltkit/admin-shadcn': '^1.1.0',
  '@basaltkit/ai-mcp': '^0.1.0',
  '@basaltkit/auth': '^3.1.0',
  '@basaltkit/auth-prisma': '^1.6.0',
  '@basaltkit/cli': '^1.2.0',
  '@basaltkit/config': '^1.1.0',
  '@basaltkit/core': '^1.4.0',
  '@basaltkit/env': '^3.1.0',
  '@basaltkit/events': '^1.3.0',
  '@basaltkit/fastify': '^2.3.0',
  '@basaltkit/generator': '^1.5.0',
  '@basaltkit/logger': '^1.3.0',
  '@basaltkit/mcp': '^3.0.0',
  '@basaltkit/prisma': '^2.2.0',
  '@basaltkit/sdk': '^2.1.0',
  '@basaltkit/subscriptions': '^4.0.0',
  '@basaltkit/subscriptions-prisma': '^2.2.0',
  '@basaltkit/teams': '^3.0.0',
  '@basaltkit/teams-prisma': '^1.0.0',
  '@basaltkit/tenancy': '^2.0.0',
  '@basaltkit/tenancy-prisma': '^1.2.0',
  '@basaltkit/testing': '^2.0.0',
}
