import { describe, expect, it } from 'vitest'
import {
  handleNotification,
  watchConnection,
  type DriveNotificationInput,
  type DriveConnection,
} from '@basaltkit/drives'
import { GRAPH_MAX_SUBSCRIPTION_MS } from '../src/index.js'
import { connect, harness, type Harness } from './helpers.js'

const NOTIFICATION_URL = 'https://app.test/drives/microsoft/notifications'

/** One Graph change-notification delivery. */
function delivery(entries: readonly Record<string, unknown>[]): DriveNotificationInput {
  return {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    query: {},
    body: Buffer.from(JSON.stringify({ value: entries })),
  }
}

function entry(clientState: string, subscriptionId = 'sub-1'): Record<string, unknown> {
  return {
    subscriptionId,
    clientState,
    changeType: 'updated',
    resource: 'me/drive/root',
    resourceData: { '@odata.type': '#Microsoft.Graph.DriveItem' },
    subscriptionExpirationDateTime: '2026-07-01T00:00:00Z',
  }
}

async function watched(h: Harness): Promise<{ connection: DriveConnection; secret: string; watchId: string }> {
  const view = await connect(h)
  const watch = await watchConnection(h.drives, view.id, { notificationUrl: NOTIFICATION_URL })
  const connection = (await h.store.find('default', view.id))!
  return { connection, secret: connection.watch!.secret, watchId: watch.id }
}

describe('the validation handshake', () => {
  it('echoes the validationToken without consulting any connection', () => {
    const h = harness()
    // Graph POSTs this **while creating the subscription** — before the
    // subscription exists, so a route that looked a connection up first could
    // never answer it. `DriveNotificationResult.challenge` is what lets the
    // shared neutral route answer all three vendors, and this adapter adds no
    // route of its own.
    const result = h.provider.verifyNotification({
      method: 'POST',
      headers: {},
      query: { validationToken: 'Validation: Testing client application reachability' },
      body: Buffer.alloc(0),
    })

    expect(result.challenge).toBe('Validation: Testing client application reachability')
    expect(result.changed).toBe(false)
    expect(result.secret).toBeUndefined()
  })

  it('reaches the engine as a challenge outcome, matching nothing', async () => {
    const h = harness()
    const outcome = await handleNotification(
      h.drives,
      { method: 'POST', headers: {}, query: { validationToken: 'abc' }, body: Buffer.alloc(0) },
      { provider: 'microsoft', connections: [] },
    )
    expect(outcome).toMatchObject({ challenge: 'abc', reason: 'challenge', shouldSync: false })
  })

  it('bounds the token it is willing to reflect', () => {
    const h = harness()
    expect(() =>
      h.provider.verifyNotification({
        method: 'POST',
        headers: {},
        query: { validationToken: 'x'.repeat(2000) },
        body: Buffer.alloc(0),
      }),
    ).toThrow(/too long/)
  })
})

describe('subscriptions', () => {
  it('registers one with the engine’s secret as clientState and surfaces the expiry', async () => {
    const h = harness()
    const view = await connect(h)

    const watch = await watchConnection(h.drives, view.id, { notificationUrl: NOTIFICATION_URL })

    const created = h.graph.subscriptions.get(watch.id)!
    const secret = (await h.store.find('default', view.id))!.watch!.secret
    // The secret is generated by the ENGINE, never by the adapter: one
    // per-subscription random value from one place is the difference between
    // "a caller needs 32 bytes of entropy" and "a caller needs to guess
    // whatever this adapter happened to use".
    expect(created.clientState).toBe(secret)
    expect(created.resource).toBe('/me/drive/root')
    // Subscriptions expire and Graph never renews them. Surfacing `expiresAt`
    // is what lets an app renew from a reconciler before it lapses.
    expect(watch.expiresAt).toBe(Date.parse(created.expirationDateTime))
    expect(watch.expiresAt! - h.now()).toBeLessThanOrEqual(GRAPH_MAX_SUBSCRIPTION_MS)
  })

  it('clamps a longer request to Graph’s ceiling rather than being refused', async () => {
    const h = harness()
    const view = await connect(h)

    await watchConnection(h.drives, view.id, {
      notificationUrl: NOTIFICATION_URL,
      ttlMs: 365 * 24 * 60 * 60_000,
    })

    const request = h.graph.requests.filter((r) => r.url.endsWith('/subscriptions')).at(-1)!
    const asked = Date.parse((JSON.parse(request.body) as { expirationDateTime: string }).expirationDateTime)
    expect(asked - h.now()).toBeLessThanOrEqual(GRAPH_MAX_SUBSCRIPTION_MS)
  })

  it('deletes the subscription on disconnect, and tolerates one that already lapsed', async () => {
    const h = harness()
    const { connection, watchId } = await watched(h)

    await h.drives.disconnect(connection.id)
    expect(h.graph.subscriptions.has(watchId)).toBe(false)
    expect(h.graph.requests.some((r) => r.method === 'DELETE' && r.url.includes('/subscriptions/'))).toBe(true)

    // A subscription Graph already expired answers 404 to the DELETE. A
    // dangling subscription is noise; a row we cannot delete is a bug.
    const second = harness()
    const other = await watched(second)
    second.graph.subscriptions.clear()
    await expect(second.drives.disconnect(other.connection.id)).resolves.toBeUndefined()
    expect(await second.store.find('default', other.connection.id)).toBeNull()
  })
})

describe('change notifications', () => {
  it('matches the connection whose clientState came back', async () => {
    const h = harness()
    const { connection, secret, watchId } = await watched(h)

    const outcome = await handleNotification(h.drives, delivery([entry(secret, watchId)]), {
      provider: 'microsoft',
      connections: [connection],
    })

    expect(outcome.shouldSync).toBe(true)
    expect(outcome.connections.map((c) => c.id)).toEqual([connection.id])
  })

  it('answers a clientState nobody holds exactly as it answers a match', async () => {
    const h = harness()
    const { connection, watchId } = await watched(h)

    const outcome = await handleNotification(h.drives, delivery([entry('not-our-secret', watchId)]), {
      provider: 'microsoft',
      connections: [connection],
    })

    // `unmatched`, not an error: answering differently turns the endpoint into
    // an oracle for which subscriptions a deployment holds.
    expect(outcome).toMatchObject({ shouldSync: false, reason: 'unmatched' })
    expect(outcome.connections).toEqual([])
  })

  it('rejects a delivery with no clientState at all', async () => {
    const h = harness()
    const { connection } = await watched(h)

    // There is no signature anywhere in Graph's webhook design: `clientState`
    // IS the authentication. A delivery without one is unauthenticated, and
    // accepting it would hand a caller a sync trigger for any connection they
    // could name.
    await expect(
      handleNotification(h.drives, delivery([{ subscriptionId: 'sub-1', changeType: 'updated' }]), {
        provider: 'microsoft',
        connections: [connection],
      }),
    ).rejects.toMatchObject({ code: 'DRIVE_NOTIFICATION_INVALID' })
  })

  it('rejects a body that is not a Graph notification', async () => {
    const h = harness()
    for (const body of [Buffer.from('not json'), Buffer.from('{}'), Buffer.from('{"value":[]}')]) {
      expect(() =>
        h.provider.verifyNotification({ method: 'POST', headers: {}, query: {}, body }),
      ).toThrow(/DRIVE_NOTIFICATION_INVALID|notification/)
    }
  })

  it('fans a batched delivery out to every subscription it names', async () => {
    const h = harness()
    const first = await watched(h)
    const secondView = await connect(h, { label: 'OneDrive HR' })
    await watchConnection(h.drives, secondView.id, { notificationUrl: NOTIFICATION_URL })
    const second = (await h.store.find('default', secondView.id))!

    // One POST, two subscriptions — which happens whenever two connections
    // share a notification URL, i.e. always. Reporting only the first
    // `clientState` would sync one and leave the other stale for as long as
    // nothing else touched it.
    const outcome = await handleNotification(
      h.drives,
      delivery([entry(first.secret, first.watchId), entry(second.watch!.secret, second.watch!.id)]),
      { provider: 'microsoft', connections: [first.connection, second] },
    )

    expect(outcome.shouldSync).toBe(true)
    expect(outcome.connections.map((c) => c.id).sort()).toEqual([first.connection.id, second.id].sort())
  })

  it('does not let one tenant’s batch reach another tenant’s connection', async () => {
    const h = harness()
    const acme = await connect(h, { tenantId: 'acme' })
    await watchConnection(h.drives, acme.id, { tenantId: 'acme', notificationUrl: NOTIFICATION_URL })
    const globex = await connect(h, { tenantId: 'globex' })
    await watchConnection(h.drives, globex.id, { tenantId: 'globex', notificationUrl: NOTIFICATION_URL })
    const acmeRow = (await h.store.find('acme', acme.id))!
    const globexRow = (await h.store.find('globex', globex.id))!

    const outcome = await handleNotification(h.drives, delivery([entry(acmeRow.watch!.secret, acmeRow.watch!.id)]), {
      provider: 'microsoft',
      connections: [acmeRow, globexRow],
    })

    expect(outcome.connections.map((c) => c.tenantId)).toEqual(['acme'])
  })

  it('treats a lifecycle event as authenticated but not as a change', async () => {
    const h = harness()
    const { connection, secret, watchId } = await watched(h)

    const outcome = await handleNotification(
      h.drives,
      delivery([{ subscriptionId: watchId, clientState: secret, lifecycleEvent: 'reauthorizationRequired' }]),
      { provider: 'microsoft', connections: [connection] },
    )

    // It means "this subscription needs attention", not "there is new work".
    // Syncing on it would be busywork; rejecting it would hide a real signal.
    expect(outcome).toMatchObject({ shouldSync: false, reason: 'no-change' })
    expect(outcome.connections.map((c) => c.id)).toEqual([connection.id])
  })

  it('never lets the clientState reach anything the app logs', async () => {
    const h = harness()
    const { connection, secret, watchId } = await watched(h)
    const outcome = await handleNotification(h.drives, delivery([entry(secret, watchId)]), {
      provider: 'microsoft',
      connections: [connection],
    })

    // `toView` strips the watch secret; the outcome carries the raw connection
    // for the app to sync, and that is the only place it exists.
    const view = await h.drives.get(connection.id)
    expect(JSON.stringify(view)).not.toContain(secret)
    expect(view.watching).toBe(true)
    expect(outcome.shouldSync).toBe(true)
  })
})
